config/routes.rb
Rails.application.routes.draw do
  devise_for  :users,
              controllers: { registrations: 'users/registrations' },
              path: '',
              path_names: {
                sign_up: 'join',
                sign_in: 'login',
                sign_out: 'logout',
                edit: 'settings'
              }

  get 'list/new' => 'list_pages#create', as: :new_list
  get 'l/:hex_id' => 'list_pages#show', as: :list_page_by_hex_id

  resources :lists do
    resources :list_shares
  end

  get 'home' => 'home#homepage'
  get 'blankpage' => 'list_pages#blankpage'
  get 'sample' => 'list_pages#sample'

  get 'subscribe' => 'subscriptions#index'
  get 'subscribe/complete_checkout' => 'subscriptions#complete_checkout'
  get 'thankyou' => 'subscriptions#thankyou'
  get 'subscribe/checkout' => 'subscriptions#get_stripe_checkout_session'
  get 'subscribe/manage' => 'subscriptions#manage_subscription', as: :manage_subscription

  get 'welcome' => 'list_pages#show', defaults: { handle: 'welcome' }, as: :welcome_list
  get 'preferences' => 'list_pages#show', defaults: { handle: 'preferences' }, as: :preferences
  get ':username' => 'list_pages#index', as: :profile_page
  get ':username/:handle' => 'list_pages#show', as: :list_page
  get ':username/:handle/deleted' => 'list_pages#show_deleted', as: :list_page_deleted

  root :to => 'home#index'
  get '*path' => 'application#render_404'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, except: :index

  def index
    if current_user
      homepage
    else
      redirect_to new_session_path(:user)
    end
  end

  def homepage
    @user = current_user
    @lists = @user.lists.where(list_type: [nil, 'welcome']).order('updated_at desc')
    @theme = @user.default_theme
    @font = @user.default_font
    render template: 'home/index'
  end

end

app/views/home/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.4/css/materialize.min.css" integrity="sha384-VP0GfisErC22dnswxVzLKdy1z+wIV3p/iGyahqdhsuFvfu9wrRUaXUAdLWPN7E8m" crossorigin="anonymous">
<header id="header">
  <a href="/"><img id="logo" src="/logo-blue-black.svg"></a>
  <span id="version"><%= Rails.application.config.calculist_version %></span>
  <% if current_user.must_confirm_email? %>
    <div class="header-message">Make sure to <a href="<%= new_confirmation_path(:user) %>">confirm your email</a> so you do not lose access to your account.</div>
  <% end %>
  <div class="header-right">
    <span id="username"><%= current_user.username %></span>
    <div class="nav-menu-container">
      <ul class="nav-menu">
        <li><a href="/settings">settings</a></li>
        <li><a href="/preferences">preferences</a></li>
        <li><span id="sign-out">sign out</span></li>
      </ul>
    </div>
  </div>
</header>

<div class="container" style="font-family:Ubuntu;min-height:100vh;max-width:800px;">
  <div class="row right-align">
    <a href="<%= new_list_path %>" class="waves-effect waves-light btn-small light-blue text-white" style="color:#fff;margin-right:0;">+ new list</a>
  </div>
  <% @lists.each do |list| %>
    <a href="<%= list_page_by_hex_id_path(hex_id: list.hex_id) %>">
      <div class="row card-panel hoverable">
        <div class="col s3"><b><%= list.title %></b></div>
        <div class="col s3" style="font-family: 'Courier New', Courier, monospace;"><%= list.hex_id %></div>
        <div class="col s3 right-align">created: <b><%= list.created_at.to_date %></b></div>
        <div class="col s3 right-align">updated: <b><%= list.updated_at.to_date %></b></div>
      </div>
    </a>
  <% end %>
</div>

<%= javascript_include_tag "homepage" %>