config/routes.rb
Rails.application.routes.draw do
  devise_for  :users,
              controllers: { registrations: 'users/registrations' },
              path: '',
              path_names: {
                sign_up: 'join',
                sign_in: 'login',
                sign_out: 'logout',
                edit: 'settings'
              }

  get 'list/new' => 'list_pages#create', as: :new_list
  get 'l/:hex_id' => 'list_pages#show', as: :list_page_by_hex_id

  resources :lists do
    resources :list_shares
  end

  get 'home' => 'home#homepage'
  get 'blankpage' => 'list_pages#blankpage'
  get 'sample' => 'list_pages#sample'

  get 'subscribe' => 'subscriptions#index'
  get 'subscribe/complete_checkout' => 'subscriptions#complete_checkout'
  get 'thankyou' => 'subscriptions#thankyou'
  get 'subscribe/checkout' => 'subscriptions#get_stripe_checkout_session'
  get 'subscribe/manage' => 'subscriptions#manage_subscription', as: :manage_subscription

  get 'welcome' => 'list_pages#show', defaults: { handle: 'welcome' }, as: :welcome_list
  get 'preferences' => 'list_pages#show', defaults: { handle: 'preferences' }, as: :preferences
  get ':username' => 'list_pages#index', as: :profile_page
  get ':username/:handle' => 'list_pages#show', as: :list_page
  get ':username/:handle/deleted' => 'list_pages#show_deleted', as: :list_page_deleted

  root :to => 'home#index'
  get '*path' => 'application#render_404'
end

app/controllers/list_pages_controller.rb
class ListPagesController < ApplicationController
  before_action :authenticate_user!, except: [:blankpage, :sample]

  def index
    @user = User.where(username: params[:username]).first
    if @user.nil? || @user != current_user
      # TODO make a public profile page instead of 404
      render_404
      return
    end
    @lists = @user.lists.where(list_type: ['user_preferences', nil]).order('updated_at desc')
    @list = @user.primary_list
    @list.content['items'].unshift(get_profile_page_list_of_lists)
    @other_lists = get_title_handle_path_id(@lists, @user)
    @theme = @user.default_theme
    @font = @user.default_font
  end

  def show
    if params[:hex_id]
      @list = List.where(hex_id: params[:hex_id]).first
      return render_404 if @list.nil?
      @list_owner = User.find(@list.user_id)
    else
      if params[:username]
        @list_owner = User.where(username: params[:username]).first
        return render_404 if @list_owner.nil?
      end
      @list_owner ||= current_user
      @list = List.where(handle: params[:handle], user_id: @list_owner.id).first
      if @list.nil? && @list_owner.id == current_user.id && params[:handle] == 'welcome'
        @list = @list_owner.welcome_list
      end
      return show_non_existent if @list.nil?
    end
    return show_non_existent unless current_user_can_read?
    return redirect_to(profile_page_path(username: @list_owner.username)) if @list.is_user_primary?
    @lists = current_user.lists
    @other_lists = get_title_handle_path_id(@lists, current_user)
    @theme = @list_owner.default_theme
    @font = @list_owner.default_font
  end

  def show_non_existent
    @error_message = "This list does not exist."
    render_404
  end

  def show_deleted
    # TODO Make this page actionable, i.e. allow the user to
    # do something with the deleted items on this page.
    @list_owner = User.where(username: params[:username]).first
    return render_404 if @list_owner.nil?
    @list = List.where(handle: params[:handle], user_id: @list_owner.id).first
    if @list && current_user_can_write?
      im = ItemManager.new(@list.id)
      days_ago = [params[:days_ago].to_i, 1].max
      @recently_deleted_items = im.get_recently_deleted(days_ago)
    else
      return render_404
    end
    @lists = current_user.lists
  end

  def create
    @list = List.new(user_id: current_user.id)
    @list.title = params[:title] if params[:title]
    @list.handle = params[:handle] if params[:handle]
    @list.default_values
    @list.save!
    if params[:handle]
      redirect_to list_page_path(username: current_user.username, handle: @list.handle)
    else
      redirect_to list_page_by_hex_id_path(hex_id: @list.hex_id)
    end
  end

  def blankpage
  end

  def sample
    @json = (@@sample_doc ||= File.read("#{Rails.root}/config/lists/sample_doc.calculist"))
    @list_title = '\emoji[U+1F4DD] Sample Document'
    render 'static_list'
  end

private

  # NOTE Should these methods be User model methods?
  def current_user_can(access_types)
    current_user.id == @list.user_id || access_types.include?(current_user.access_to_list(@list))
  end

  def current_user_can_read?
    current_user_can(['read_write','read_only'])
  end

  def current_user_can_write?
    current_user_can(['read_write'])
  end

  def get_title_handle_path_id(lists, user)
    lists.map { |list| { title: list.title, handle: list.handle, path: list_page_path(username: user.username, handle: list.handle), id: list.id } }
  end

  def get_profile_page_list_of_lists
    inc = 0
    {
      text: 'lists',
      guid: "do_not_save#{inc += 1}",
      'items': @lists.map do |list| {
        text: list.title,
        collapsed: true,
        guid: "do_not_save#{inc += 1}",
        'items': [
          {
            text: "handle [:] #{list.handle}",
            guid: "do_not_save#{inc += 1}"
          },{
            text: "created_at [:] #{list.created_at}",
            guid: "do_not_save#{inc += 1}"
          },{
            text: "updated_at [:] #{list.updated_at}",
            guid: "do_not_save#{inc += 1}",
          },{
            text: "update_count [:] #{list.update_count}",
            guid: "do_not_save#{inc += 1}"
          },{
            text: "item_count [:] #{list.items.where(is_deleted: false).pluck('count(*)')[0]}",
            guid: "do_not_save#{inc += 1}",
          },{
            text: "shared_with [=] count($items)",
            guid: "do_not_save#{inc += 1}",
            'items': list.list_shares.map { |ls| { text: "#{ls.user.username} [:] #{ls.access_type}" } }
          }
        ]
      } end
    }
  end

end

app/views/list_pages/blankpage.html.erb
<header id="header">
  <a href="/"><img id="logo" src="/logo-blue-black.svg"></a>
  <span id="version"><%= Rails.application.config.calculist_version %></span>
  <div class="header-right">
    <% if current_user %>
      <span id="username"><a href="/<%= current_user.username %>"><%= current_user.username %></a></span>&nbsp;|&nbsp;<span id="sign-out">sign out</span>
    <% else %>
      <span><a href="<%= new_registration_path(:user) %>">sign up</a></span>&nbsp;|&nbsp;<span><a href="<%= new_session_path(:user) %>">sign in</a></span>
    <% end %>
  </div>
</header>

<div class="page main-page">
  <ul id="top-level"></ul>
</div>

<input type="file" style="display:none;">

<script>
  var LIST_TITLE = "Calculist",
      LIST_DATA = {},
      LIST_ID = 0,
      INITIAL_LAST_SAVE = 0,
      USER_PREFERENCES = <%= raw(current_user ? current_user.preferences.content.to_json : UserPreferencesManager::DEFAULT_PREFERENCES.to_json) %>,
      WORKER_FILE_PATH = '<%= asset_path('worker.js') %>',
      READ_ONLY = false,
      OTHER_LISTS = [];
</script>

<%= javascript_include_tag "vendor" %>
<%= javascript_include_tag "application" %>

app/views/list_pages/index.html.erb
<header id="header">
  <a href="/"><img id="logo" src="/logo-blue-black.svg"></a>
  <span id="version"><%= Rails.application.config.calculist_version %></span>
  <% if current_user.must_confirm_email? %>
    <div class="header-message">Make sure to <a href="<%= new_confirmation_path(:user) %>">confirm your email</a> so you do not lose access to your account.</div>
  <% end %>
  <div class="header-right">
    <span id="save-status">saved</span>&nbsp;|&nbsp;<span id="username"><%= current_user.username %></span>&nbsp;|&nbsp;<span id="sign-out">sign out</span>
  </div>
</header>

<div class="page main-page">
  <ul id="top-level"></ul>
</div>

<input type="file" style="display:none;">

<script>
  var LIST_TITLE = "<%= @list.title.gsub("\n", '') %>",
      LIST_DATA = <%= raw(@list.content.to_json) %>,
      LIST_ID = <%= @list.id %>,
      INITIAL_LAST_SAVE = <%= @list.update_count || 0 %>,
      USER_PREFERENCES = <%= @list.list_type == 'user_preferences' ? 'null' : raw(current_user.preferences.content.to_json) %>,
      WORKER_FILE_PATH = '<%= asset_path('worker.js') %>',
      READ_ONLY = false,
      OTHER_LISTS = <%= raw(@other_lists.to_json) %>;
</script>

<%= javascript_include_tag "vendor" %>
<%= javascript_include_tag "application" %>

app/views/list_pages/show.html.erb
<header id="header">
  <a href="/"><img id="logo" src="/logo-blue-black.svg"></a>
  <span id="version"></span>
  <% if current_user.must_confirm_email? %>
    <div class="header-message">Make sure to <a href="<%= new_confirmation_path(:user) %>">confirm your email</a> so you do not lose access to your account.</div>
  <% end %>
  <div class="header-right">
    <span id="save-status">saved</span>&nbsp;|&nbsp;<span id="username"><a href="/<%= current_user.username %>"><%= current_user.username %></a>
    <div class="nav-menu-container">
      <ul class="nav-menu">
        <li><a href="/settings">settings</a></li>
        <li><a href="/preferences">preferences</a></li>
        <li><span id="sign-out">sign out</span></li>
      </ul>
    </div>
  </div>
</header>

<div class="page main-page">
  <ul id="top-level"></ul>
</div>

<footer id="footer">
</footer>

<input type="file" style="display:none;">

<script>
  var LIST_TITLE = "<%= @list.title.gsub("\n", '') %>",
      LIST_DATA = <%= raw(@list.content.to_json) %>,
      LIST_ID = <%= @list.id %>,
      INITIAL_LAST_SAVE = <%= @list.update_count || 0 %>,
      USER_PREFERENCES = <%= @list.list_type == 'user_preferences' ? 'null' : raw(current_user.preferences.content.to_json) %>,
      WORKER_FILE_PATH = '<%= asset_path('worker.js') %>',
      READ_ONLY = false,
      OTHER_LISTS = <%= raw(@other_lists.to_json) %>;
</script>

<%= javascript_include_tag "vendor" %>
<%= javascript_include_tag "application" %>

app/views/list_pages/show.json.erb
<%= raw(@list.content.to_json) %>

app/views/list_pages/show.text.erb
<%
def get_text(content, depth)
  txt = "#{' ' * depth}#{content['text']}\n"
  content['items'].each do |item|
    txt += get_text(item, depth + 2)
  end
  txt
end
%><%= get_text(@list.content, 0).chomp("\n") %>

app/views/list_pages/show_deleted.html.erb
<header id="header">
  <img id="logo" src="/logo-blue-black.svg">
  <div class="header-right">
    <span id="sign-out">sign out</span>
  </div>
</header>

<div class="page main-page">
  <% @recently_deleted_items.each do |update_object| %>
    <div class="page">
      <h2>[<%= update_object[:luid] %>] <%= update_object[:updated_at] %></h2>
      <ul>
        <% update_object[:items].each do |item| %>
          <li>
            <span><%= item['text'] %></span>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<script>

</script>

app/views/list_pages/static_list.html.erb
<header id="header">
  <a href="/"><img id="logo" src="/logo-blue-black.svg"></a>
  <span id="version"></span>
  <div class="header-right">
    <% if current_user %>
      <span id="username"><a href="/<%= current_user.username %>"><%= current_user.username %></a>
      <div class="nav-menu-container">
        <ul class="nav-menu">
          <li><a href="/settings">settings</a></li>
          <li><a href="/preferences">preferences</a></li>
          <li><span id="sign-out">sign out</span></li>
        </ul>
      </div>
    <% else %>
      <span><a href="<%= new_registration_path(:user) %>">sign up</a></span>&nbsp;|&nbsp;<span><a href="<%= new_session_path(:user) %>">sign in</a></span>
    <% end %>
  </div>
</header>

<div class="page main-page">
  <ul id="top-level"></ul>
</div>

<footer id="footer">
</footer>

<input type="file" style="display:none;">

<script>
  var LIST_TITLE = "<%= @list_title.gsub("\n", '') %>",
      LIST_DATA = <%= raw(@json) %>,
      LIST_ID = 0,
      INITIAL_LAST_SAVE = 0,
      USER_PREFERENCES = <%= raw(current_user ? current_user.preferences.content.to_json : UserPreferencesManager::DEFAULT_PREFERENCES.to_json) %>,
      WORKER_FILE_PATH = '<%= asset_path('worker.js') %>',
      READ_ONLY = true,
      OTHER_LISTS = [];
</script>

<%= javascript_include_tag "vendor" %>
<%= javascript_include_tag "application" %>